"""The filter builder's catalog must keep up with the filter language.

The builder (P1-15) lists one entry per predicate in
``frontend/src/features/crm/predicates.ts``. Its own vitest suite compares that
list with the discriminator mapping in ``frontend/openapi.json``, which is the
published contract and is regenerated by ``make gen-client``.

What that comparison cannot see is *which* predicates the compiler still
refuses: ``PLACEHOLDERS`` is a Python dict with no place in the schema. So the
check lives here, where it runs under ``make check`` and fails the moment a
placeholder graduates — the day ``list_member`` compiles (issue #73), this test
fails until the builder stops telling people it does not.

That day came with P1-27, and it turned one set into two. The builder greys a
predicate out for either of two reasons now: the compiler refuses it
(``PLACEHOLDERS``), or the compiler takes it and the *builder* has nothing to
edit it with (:data:`BUILDER_ONLY`). Both are honest, and they read the same
on screen, but only the first is a statement about the server — so a
builder-only entry may not claim the server refuses it, and the day the
builder grows the editor it needs, that op leaves :data:`BUILDER_ONLY` rather
than quietly widening what "unavailable" means.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from netkeeper.crm.filters import OPS, PLACEHOLDERS

CATALOG = Path(__file__).resolve().parents[1] / "frontend/src/features/crm/predicates.ts"

# An entry starts with its own `op:` line at the object's indentation. The
# `op` inside a nested `create()` or `example` sits further in on its line, so
# it never matches.
_ENTRY_OP = re.compile(r"^    op: '([a-z_]+)',$", re.MULTILINE)


def _entries() -> dict[str, str]:
    """Each predicate's catalog entry, by op: the text from its `op:` to the next one."""
    text = CATALOG.read_text(encoding="utf-8")
    marks = [(match.start(), match.group(1)) for match in _ENTRY_OP.finditer(text)]
    assert marks, f"no predicate entries found in {CATALOG}"
    bounds = [*(start for start, _ in marks), len(text)]
    return {op: text[bounds[index] : bounds[index + 1]] for index, (_, op) in enumerate(marks)}


@pytest.fixture(scope="module")
def entries() -> dict[str, str]:
    if not CATALOG.exists():
        pytest.fail(f"the filter builder's catalog is missing: {CATALOG}")
    return _entries()


def test_catalog_lists_every_predicate(entries: dict[str, str]) -> None:
    assert sorted(entries) == sorted(OPS)


BUILDER_ONLY: frozenset[str] = frozenset()
"""Ops the compiler takes that the builder still cannot offer.

Empty, and the shape is what matters: ``list_member`` was here between P1-27
(#73), which taught the compiler to inline a list, and P1-28, which gave the
builder the picker that names one. An op belongs here only while the builder
is the thing missing, and it leaves by getting its editor rather than by being
re-explained.
"""


def _reason(body: str) -> str:
    return body.split("unavailable:", 1)[1].split("create:", 1)[0].strip()


def test_catalog_marks_the_placeholders_and_nothing_else_it_cannot_explain(
    entries: dict[str, str],
) -> None:
    marked = {op for op, body in entries.items() if "unavailable:" in body}
    assert set(PLACEHOLDERS) <= marked, (
        "the builder offers a predicate filters.PLACEHOLDERS says the compiler refuses; "
        "the person would build a filter the server answers 422 for"
    )
    assert marked - set(PLACEHOLDERS) == BUILDER_ONLY, (
        "the builder greys out a predicate the compiler accepts and this test does not "
        "know about; add it to BUILDER_ONLY with a reason, or give the builder its editor"
    )


def test_each_placeholder_says_why(entries: dict[str, str]) -> None:
    for op in PLACEHOLDERS:
        body = entries[op]
        assert "unavailable:" in body, f"{op} is a placeholder with no reason for the UI"
        assert len(_reason(body)) > 40, f"{op}'s reason is too short to be useful"


def test_a_builder_only_entry_does_not_blame_the_server(entries: dict[str, str]) -> None:
    """It compiles; saying otherwise sends people to a bug that is not there."""
    for op in BUILDER_ONLY:
        reason = _reason(entries[op])
        assert len(reason) > 40, f"{op}'s reason is too short to be useful"
        assert "server refuses" not in reason, (
            f"{op} compiles now; its reason still says the server refuses it"
        )
