"""The filter builder's catalog must keep up with the filter language.

The builder (P1-15) lists one entry per predicate in
``frontend/src/features/crm/predicates.ts``. Its own vitest suite compares that
list with the discriminator mapping in ``frontend/openapi.json``, which is the
published contract and is regenerated by ``make gen-client``.

What that comparison cannot see is *which* predicates the compiler still
refuses: ``PLACEHOLDERS`` is a Python dict with no place in the schema. So the
check lives here, where it runs under ``make check`` and fails the moment a
placeholder graduates — the day ``list_member`` compiles (issue #73), this test
fails until the builder stops telling people it does not.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from netkeeper.crm.filters import OPS, PLACEHOLDERS

CATALOG = Path(__file__).resolve().parents[1] / "frontend/src/features/crm/predicates.ts"

# An entry starts with its own `op:` line at the object's indentation. The
# `op` inside a nested `create()` or `example` sits further in on its line, so
# it never matches.
_ENTRY_OP = re.compile(r"^    op: '([a-z_]+)',$", re.MULTILINE)


def _entries() -> dict[str, str]:
    """Each predicate's catalog entry, by op: the text from its `op:` to the next one."""
    text = CATALOG.read_text(encoding="utf-8")
    marks = [(match.start(), match.group(1)) for match in _ENTRY_OP.finditer(text)]
    assert marks, f"no predicate entries found in {CATALOG}"
    bounds = [*(start for start, _ in marks), len(text)]
    return {op: text[bounds[index] : bounds[index + 1]] for index, (_, op) in enumerate(marks)}


@pytest.fixture(scope="module")
def entries() -> dict[str, str]:
    if not CATALOG.exists():
        pytest.fail(f"the filter builder's catalog is missing: {CATALOG}")
    return _entries()


def test_catalog_lists_every_predicate(entries: dict[str, str]) -> None:
    assert sorted(entries) == sorted(OPS)


def test_catalog_marks_exactly_the_placeholders(entries: dict[str, str]) -> None:
    marked = {op for op, body in entries.items() if "unavailable:" in body}
    assert marked == set(PLACEHOLDERS), (
        "the builder's 'not available yet' set no longer matches filters.PLACEHOLDERS; "
        "a predicate either graduated or stopped compiling"
    )


def test_each_placeholder_says_why(entries: dict[str, str]) -> None:
    for op in PLACEHOLDERS:
        body = entries[op]
        assert "unavailable:" in body, f"{op} is a placeholder with no reason for the UI"
        reason = body.split("unavailable:", 1)[1].split("create:", 1)[0]
        assert len(reason.strip()) > 40, f"{op}'s reason is too short to be useful"
