/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'
import { Route as ImportsIndexRouteImport } from './routes/imports.index'
import { Route as ImportsRunsIndexRouteImport } from './routes/imports.runs.index'
import { Route as ImportsRunsRunIdRouteImport } from './routes/imports.runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsIndexRoute = ImportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImportsRoute,
} as any)
const ImportsRunsIndexRoute = ImportsRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => ImportsRoute,
} as any)
const ImportsRunsRunIdRoute = ImportsRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => ImportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/exports': typeof ExportsRoute
  '/imports': typeof ImportsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/linkedin': typeof LinkedinRoute
  '/lists': typeof ListsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/triage': typeof TriageRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/': typeof ContactsIndexRoute
  '/imports/': typeof ImportsIndexRoute
  '/imports/runs/$runId': typeof ImportsRunsRunIdRoute
  '/imports/runs/': typeof ImportsRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/exports': typeof ExportsRoute
  '/inbox': typeof InboxRoute
  '/linkedin': typeof LinkedinRoute
  '/lists': typeof ListsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/triage': typeof TriageRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts': typeof ContactsIndexRoute
  '/imports': typeof ImportsIndexRoute
  '/imports/runs/$runId': typeof ImportsRunsRunIdRoute
  '/imports/runs': typeof ImportsRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/exports': typeof ExportsRoute
  '/imports': typeof ImportsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/linkedin': typeof LinkedinRoute
  '/lists': typeof ListsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/triage': typeof TriageRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/': typeof ContactsIndexRoute
  '/imports/': typeof ImportsIndexRoute
  '/imports/runs/$runId': typeof ImportsRunsRunIdRoute
  '/imports/runs/': typeof ImportsRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/exports'
    | '/imports'
    | '/inbox'
    | '/linkedin'
    | '/lists'
    | '/settings'
    | '/templates'
    | '/triage'
    | '/contacts/$contactId'
    | '/contacts/'
    | '/imports/'
    | '/imports/runs/$runId'
    | '/imports/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/exports'
    | '/inbox'
    | '/linkedin'
    | '/lists'
    | '/settings'
    | '/templates'
    | '/triage'
    | '/contacts/$contactId'
    | '/contacts'
    | '/imports'
    | '/imports/runs/$runId'
    | '/imports/runs'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/exports'
    | '/imports'
    | '/inbox'
    | '/linkedin'
    | '/lists'
    | '/settings'
    | '/templates'
    | '/triage'
    | '/contacts/$contactId'
    | '/contacts/'
    | '/imports/'
    | '/imports/runs/$runId'
    | '/imports/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRoute
  ExportsRoute: typeof ExportsRoute
  ImportsRoute: typeof ImportsRouteWithChildren
  InboxRoute: typeof InboxRoute
  LinkedinRoute: typeof LinkedinRoute
  ListsRoute: typeof ListsRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  TriageRoute: typeof TriageRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/': {
      id: '/imports/'
      path: '/'
      fullPath: '/imports/'
      preLoaderRoute: typeof ImportsIndexRouteImport
      parentRoute: typeof ImportsRoute
    }
    '/imports/runs/': {
      id: '/imports/runs/'
      path: '/runs'
      fullPath: '/imports/runs/'
      preLoaderRoute: typeof ImportsRunsIndexRouteImport
      parentRoute: typeof ImportsRoute
    }
    '/imports/runs/$runId': {
      id: '/imports/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/imports/runs/$runId'
      preLoaderRoute: typeof ImportsRunsRunIdRouteImport
      parentRoute: typeof ImportsRoute
    }
  }
}

interface ImportsRouteChildren {
  ImportsIndexRoute: typeof ImportsIndexRoute
  ImportsRunsRunIdRoute: typeof ImportsRunsRunIdRoute
  ImportsRunsIndexRoute: typeof ImportsRunsIndexRoute
}

const ImportsRouteChildren: ImportsRouteChildren = {
  ImportsIndexRoute: ImportsIndexRoute,
  ImportsRunsRunIdRoute: ImportsRunsRunIdRoute,
  ImportsRunsIndexRoute: ImportsRunsIndexRoute,
}

const ImportsRouteWithChildren =
  ImportsRoute._addFileChildren(ImportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRoute,
  ExportsRoute: ExportsRoute,
  ImportsRoute: ImportsRouteWithChildren,
  InboxRoute: InboxRoute,
  LinkedinRoute: LinkedinRoute,
  ListsRoute: ListsRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  TriageRoute: TriageRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  ContactsIndexRoute: ContactsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
